services:
  api:
    image: jcoker91/nta-api:dev
    ports:
      - "8000:80"
    env_file:
      - .config/api.env.dev
  web:
    image: jcoker91/nta-web:dev
    ports:
      - "80:80"
    env_file:
      - .config/frontend.env.dev
    links:
      - api
