name: Merge to main

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: create pull request
        run: gh pr create -B main -H test --title 'Merge test into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
