name: Test
on:
  pull_request:
    branches: ["main"]
    types: opened
jobs:
  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        working-directory: ./frontend/
        run: flutter pub get
      - name: Run tests
        working-directory: ./frontend/
        run: flutter test
  backend_tests:
    needs: frontend_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v2
      - name: Install dependencies
        working-directory: ./backend/
        run: pip install flake8
      - name: Run tests
        working-directory: ./backend/
        run: flake8 .
      - name: install pip dependencies
        working-directory: ./backend/
        run: pip install -r requirements.txt
      - name: Run tests
        working-directory: ./backend/
        run: pytest
