name: Test
on:
  pull_request:
    branches: ["test"]
    types: closed
jobs:
  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        working-directory: ./frontend/
        run: flutter pub get
      - name: Run tests
        working-directory: ./frontend/
        run: flutter test
  backend_tests:
    needs: frontend_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test
      - uses: actions/setup-python@v2
      - name: Install dependencies
        working-directory: ./backend/
        run: pip install flake8
      - name: Run tests
        working-directory: ./backend/
        run: flake8 .
      - name: install pip dependencies
        working-directory: ./backend/
        run: pip install -r requirements.txt
      - name: Run tests
        working-directory: ./backend/
        run: pytest
  merge:
    needs: [frontend_tests, backend_tests]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test
      - name: create pull request
        run: gh pr create -B main -H test --title 'Merge test into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: merge pull request
        run: gh pr merge --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: rebase test branch
        run: git rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
